config/routes.rb
Rails.application.routes.draw do
  resources :users

  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create]do
    delete :destroy, on: :collection
  end

  resources :products do
    resources :reviews, only: [:create, :destroy] do
      resources :likes, only: [:create, :destroy]
    end
      resources :favourites, only: [:create, :destroy]

  end

  resources :favourites, only: [:index]

  root "products#index"

  get "/favourites" => "favourites#index", as: :user_favourites

end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :review

  validates :user_id, uniqueness: {scope: :review_id}
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!


  def create
    @like           = current_user.likes.new
    @review         = Review.find params[:review_id]
    @like.review    = @review
    @product        = params[:product_id]
    respond_to do |format|
      if @like.save
        format.html { redirect_to product_path(@review.product), notice: "Liked!" }
        format.js { render }
      else
        format.html { redirect_to product_path(@review.product), alert: "Already Liked!" }
        format.js { render js: "alert('Can\'t like!');" }
      end
    end
  end

  def destroy
    @like = current_user.likes.find params[:id]
    @like.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: "Un-liked!" }
      format.js { render }
    end
  end

private

def review
  @review ||= Review.find params[:question_id]
end

def like
  @like ||= Like.find params[:id]
end

end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_review_like.html.erb
<% if review.likes.where(user_id: current_user.id).present? %>
  <%- @user_like = review.likes.where(user_id: current_user.id).first %>
  <%= link_to "Un-Like", product_review_like_path((@product || product), review,  @user_like), method: :delete, remote: true %>
<% else %>
  <%= link_to "like", product_review_likes_path((@product || product), review), method: :post, remote: true %>
<% end %>
(<%= @review.likes.count %>)

app/views/likes/create.js.erb
$("#review-like").html("<%= j render 'review_like', review: @review, product: @product %>")

app/views/likes/destroy.js.erb
$("#review-like").html("<% j render  %>")