config/routes.rb
Rails.application.routes.draw do
  resources :users

  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create]do
    delete :destroy, on: :collection
  end

  resources :products do
    resources :reviews, only: [:create, :destroy] do
      resources :likes, only: [:create, :destroy]
    end
      resources :favourites, only: [:create, :destroy]

  end

  resources :favourites, only: [:index]

  root "products#index"

  get "/favourites" => "favourites#index", as: :user_favourites

end

app/models/product.rb
class Product < ActiveRecord::Base

  has_many :reviews, dependent: :destroy
  has_many :favourites, dependent: :destroy
  has_many :users, through: :favourites

  def favourite_for(user)
    favourites.find_by_user_id(user)
  end

  after_initialize :default_values

  validates :title, presence: true, uniqueness: {message: "must be unique!"}

  #validates(:description,{presence: true, length: {minimum: 10}})

  validates(:price, {presence: true})
  validates :sale_price, presence: true
  validates :sale_price, numericality: {less_than_or_equal_to: :price}

  #after_initialize :set_defaults

  #before_validation :titleize_title

  private
  def default_values
    self.sale_price ||= price
  end
  #def titleize_title
  #  self.title = title.titleize
  #end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :find_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:new]
  #def new
  #  @product=Product.new
  #end

  def create
    product_params = params.require(:product).permit([:title,
                          :description, :price, :sale_price])
    @product       = Product.new(product_params)
    @product.user  = current_user

    if @product.save
      redirect_to product_path(@product)
    else
      render :new
    end
  end

  def index
    @products      = Product.all
    respond_to do |format|
      format.html { render }
      format.json { render json: @product.select(:id. :title, :description, :price, :sale_price) }
  end

  def edit
      @product     = Product.find params[:id]
    end

  def show
    @favourite     = @product.favourite_for(current_user)
    @review        = Review.new
  end

  def update
    @product       = Product.find params[:id]
    product_params = params.require(:product).permit(:title,
                          :description, :price, :sale_price)
    if @product.update product_params
      redirect_to product_path(@product)
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find params[:id]
    @product.destroy
    redirect_to products_path
  end
private

  def find_product
    @product = Product.find params[:id]
  end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/edit.html.erb
<h1>EDIT PRODUCT BOO!</h1>

<%# @product.errors.full_messages.join(", ") %>

<%# form_for is a Rails helper method that accepts an ActiveRecord object as
    the first argument.
    if @question is not persisted in the database, form_for makes the `action`
    of the form go to `questions_path` (Rails convention) and it will make the
    `method` of `form` be POST
    %>
<%= form_for @product do |f| %>
  <div>
    <%= f.label :title %>
    <%# by using f.text_field :title, if @question has a value for the attribute
        `title` it will populate the field with that value. This is usually the
        case when redisplaying the form after an error occurs %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div>
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div>
    <%= f.label :sale_price %>
    <%= f.text_field :sale_price %>
  </div>

  <%= f.submit %>
<% end %>

app/views/products/index.html.erb
<h1>All Products</h1>

<% @products.each_with_index do |prod, index| %>
<div>
  <%= index +1 %> . <%= link_to prod.title, product_path(prod) %>
</div>
<% end %>

app/views/products/new.html.erb
<h1>NEW PRODUCT BOO!</h1>

<%# @product.errors.full_messages.join(", ") %>

<%# form_for is a Rails helper method that accepts an ActiveRecord object as
    the first argument.
    if @question is not persisted in the database, form_for makes the `action`
    of the form go to `questions_path` (Rails convention) and it will make the
    `method` of `form` be POST
    %>
<%= form_for Product.new do |f| %>
  <div>
    <%= f.label :title %>
    <%# by using f.text_field :title, if @question has a value for the attribute
        `title` it will populate the field with that value. This is usually the
        case when redisplaying the form after an error occurs %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div>
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div>
    <%= f.label :sale_price %>
    <%= f.text_field :sale_price %>
  </div>
  <%= f.submit %>
<% end %>

app/views/products/show.html.erb
Name: <%= @product.title %>
<br>
Description: <%= @product.description %>
<br>
Price: $<%= @product.price %> ||
Sale Price: $<%= @product.sale_price %>

<br>

    <% if @favourite.present? && @favourite.persisted? %>
      <%= link_to "Un-Fav", product_favourite_path(@product, @favourite), method: :delete %>
    <% else %>
      <%= link_to "Favourite", product_favourites_path(@product), method: :product %>
    <% end %>

<br>

<%= link_to "Edit", edit_product_path(@product) %>
<%= link_to "Delete", product_path(@product),
    method: :delete, data: {confirm: "Are you sure?"} %>
<hr>
<%= notice || alert %>

<h3> Write A Review: </h3>
<div id="review-form">
 <%= render "/reviews/form", review: @review %>
</div>

<h2> Reviews: </h2>
<div id="reviews">
  <% @product.reviews.each do |rev| %>
    <%= render "/reviews/review", review: rev, like: @like %>
  <% end  %>
</div>

<div id="product-review-like">

</div>