config/routes.rb
Rails.application.routes.draw do
  resources :users

  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create]do
    delete :destroy, on: :collection
  end

  resources :products do
    resources :reviews, only: [:create, :destroy] do
      resources :likes, only: [:create, :destroy]
    end
      resources :favourites, only: [:create, :destroy]

  end

  resources :favourites, only: [:index]

  root "products#index"

  get "/favourites" => "favourites#index", as: :user_favourites

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Amazon</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class = "container">
  <%= link_to "Product Index", products_path %> ||
  <%= link_to "New Product", new_product_path %> ||


  <% if user_signed_in? %>
  Whaddup, Whaddup <%= current_user.first_name.titleize %>!
  <%= link_to "Logout", sessions_path, method: :delete,
            data: {confirm: "are you sure u log out?"}%> ||
      <%= link_to "Your Favs", user_favourites_path %>
  <% else %>
    <%= link_to "Login", new_session_path %> ||
    <%= link_to "Sign Up", new_user_path %> ||
  <% end %>

  <hr>
<%= yield %>
</div>

</body>
</html>

app/views/layouts/special.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Welcome</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%# link_to is a helper method that comes from Rails which generates an <a>
    HTML element. The 'link_to' method takes two pruimary arguements. The first
    argument is for the anchor text and the second argument is for the 'href'
    value (where you want to link to)%>

<%# the link_to method is the preferred method %>
  <%= link_to "Home", home_path %>

  <%= link_to "New Product", new_products_path %>

  <hr>
<%= yield %>

</body>
</html>